export const projectData = {
  recorderKarate: {
    title: "Recorder Karate",
    image: "/recorderKarate.png",
    link: "https://recorderkarate.netlify.app",
    info: "Recorder Karate was built for the Elliot Elementary school music classroom. The students use the application to progress through a series of songs to earn their belts. Recorder Karate was built using React and React Router.",
    tech: "HTML, CSS, JavaScript, React",
    date: "November 2022",
    repo: "https://github.com/patricksperanza/recorder-karate-v2",
  },
  fullStackFlashcards: {
    title: "Full Stack Flashcards",
    image: "/fullStackFlashcards.png",
    link: "https://next-flashcards.vercel.app/",
    info: "Full Stack Flashcards is a full stack study application built with Next JS. The app allows users to create, edit, and delete flashcards to study for interview questions.",
    tech: "Next JS, TypeScript, Tailwind CSS, Next-Auth, MongoDB",
    date: "June 2023",
    repo: "https://github.com/patricksperanza/flashcards",
  },
  playfulPiano: {
    title: "Playful Piano",
    image: "/playfulPiano.png",
    link: "https://playfulpiano.netlify.app/",
    info: "Playful Piano is an interactive React application that is designed to help young children learn simple songs on the piano. The piano can be played by click or by using the keyboard.",
    tech: "HTML, CSS, JavaScript, React",
    date: "February 2023",
    repo: "https://github.com/patricksperanza/playful-piano",
  },
  gameHub: {
    title: "Game Hub",
    image: "/gameHub.png",
    link: "https://game-hub-lovat.vercel.app/",
    info: "Game Hub is a clone of the Rawg.io website built with TypeScript and React. This website was built by following Mosh Hamedi's new React and TypeScript course.",
    tech: "HTML, CSS, TypeScript, React",
    date: "March 2023",
    repo: "https://github.com/patricksperanza/game-hub",
  },
  keynotes: {
    title: "Keynotes Music",
    image: "/keynotes.png",
    link: "https://keynotesmusic.netlify.app/",
    info: "Keynotes Music is a Full Stack web application designed for private lessons teachers to manage all of their student's information. Students are able to connect to their teachers accounts and receive weekly updated with details and assignments from each lesson.",
    tech: "React, TypeScript, Express, MySQL",
    date: "September 2023",
    repo: "https://github.com/patricksperanza/keynotes-frontend",
  },
  bracketology: {
    title: "Bracketology",
    image: "/bracketology.png",
    link: "https://bracketology.vercel.app/",
    info: "Bracketology is a Full Stack web application created for a new bracktology orgnaziation and their members. Members are able to log in and upload their personalized brackets.",
    tech: "Next JS, TailWind CSS, MongoDb",
    date: "June 2023",
    repo: "https://github.com/patricksperanza/bracketology",
  },
};
